services:
 facefusion-cuda:
  build:
   dockerfile: Dockerfile.cuda
  command: [ 'python', 'run.py', '--execution-providers', 'cuda' ]
  volumes:
  - .assets/models:/facefusion/.assets/models
  ports:
  - 7880:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       count: -1
       capabilities: [ gpu, video ]
