name: ci

on: [ push, pull_request ]

jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    config:
    - { compose-file: 'docker-compose.cpu.yml', container-name: 'facefusion-cpu' }
    - { compose-file: 'docker-compose.cuda.yml', container-name: 'facefusion-cuda' }
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - run: docker-compose -f ${{ matrix.config.compose-file }} up --detach
  - run: docker-compose ps | grep --quiet ${{ matrix.config.container-name }}
